### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by robertDouglass** [LaconicNetwork/Laconic-Documentation#11]
Michael has started one here: https://docs.google.com/document/d/1RNRA1w54jJOX6hYITJEBkpRoUD85eWzlEmpks0kno9U/edit

- Interview Maly, Michael, Ian:
    Introductions
    Have them review the questions for correctness 
    Are we missing any questions?
- Answer and organize the existing questions (inspiration https://forum.thegraph.com/t/the-graph-faqs-everything-you-need-to-know/850)
- Add and answer any further questions
- Reviews by Christoph, Robert, Michael
- Publish into Hugo https://github.com/LaconicNetwork/Laconic-Documentation/tree/main/content/faq

**Comment by Jesi-OSP** [comment]
The meeting with Maly was cancelled, so will either be rescheduled or she can respond to draft by email.

**Comment by andrewjtech123** [comment]
The FAQ was written up and merged into the site
https://bafybeiarjgm5vnzzqqs6clt74uumgfgoel3yb3ntxsrsk3wxxuvefnb2za.on.fleek.co/faq/
