### ISSUE TITLE
Glossary

### ISSUE THREAD

**Issue by robertDouglass** [LaconicNetwork/Laconic-Documentation#27]
Define all the terms we want to use in public

Watcher
Validator
Service Provider
Browser Based Service Provider
Proof

ETH terms:
Header - 0x90
Uncles (Header list) - 0x91
Transaction - 0x93
Transaction Trie Node - 0x92
Receipt - 0x95
Receipt Trie Node - 0x94
State Trie Node - 0x96
State Account - 0x97
Storage Trie Node - 0x98

etc.

These will appear in the Glossary section of the Docs website:
https://github.com/LaconicNetwork/Laconic-Documentation/tree/main/content

**Comment by Jesi-OSP** [comment]
Deadline pushed to Mar 9 - Rob and Christoph to meet to discuss which terms to be selected, how many etc.

**Comment by christophberger** [comment]
Glossary items TBD:

- [ ]     Laconic Network
- [ ]     Validator
- [ ]     Service Provider
- [ ]     DApp Operator
- [ ]     Laconic Network Partner
- [ ]     Laconic Network Token (LNT)
- [ ]     Laconic Stack
- [ ]     Laconic Core
- [ ]     Watcher
- [ ]     Watcher Registry
- [ ]     Ethereum
- [ ]     Provability
- [ ]     Merkleization
- [ ]     Content Addressing
- [ ]     IPFS
- [ ]     IPLD
- [ ]     Snapshot
- [ ]     Block Height
- [ ]     Canonical Truth
- [ ]     Chain Reorganization
- [ ]     Global View of Ethereum State
- [ ]     Contract Slot
- [ ]     EVM
- [ ]     Solidity
- [ ]     Geth
- [ ]     laconic-geth
- [ ]     go-ethereum
- [ ]     devp2p
- [ ]     Statediff Object
- [ ]     TypeScript
- [ ]     WASM
- [ ]     Cosmos SDK
- [ ]     ORU (Optimistic Rollup)
- [ ]     ORU Bridge
