### ISSUE TITLE
Set up Hugo template and styling and navigation for Glossary & FAQ

### ISSUE THREAD

**Issue by robertDouglass** [LaconicNetwork/Laconic-Documentation#28]
- Where in navigation should Glossary exist?
- What is the Hugo directory and index.md structure needed?
- Are there existing styles in this or other Hugo themes that can be used?

**Comment by christophberger** [comment]
An interesting example of a Glossary/FAQ page - https://kubernetes.io/docs/reference/glossary/?fundamental=true
(Source: https://github.com/kubernetes/website/)

Found in https://discourse.gohugo.io/t/how-to-make-like-glossary-page/14182/5

**Comment by robertDouglass** [comment]
Indeed, I like that.

**Comment by christophberger** [comment]
What would be the preferred style of writing and maintaining an FAQ or a glossary?

**Comment by christophberger** [comment]
What would be the preferred approach of writing and maintaining items of an FAQ or a glossary?

1. All questions and answers (or terms and definitions) in one single file
2. Each question/answer pair (or term/definition pair) in a separate file

Example: the Kubernetes glossary (links in the previous comment) uses separate files. Every glossary entry is technically a standard Hugo page. (Sample page source [here](https://github.dev/kubernetes/website/blob/3f6efc04df10bfb8125fee382453e896e1706115/content/en/docs/reference/glossary/affinity.md))

@robertDouglass @andrewjtech123 @olive-kimoto

**Comment by robertDouglass** [comment]
i'm in favor of the one file per item approach. It's it's very important to me that each one has a Perma link. I'm not as much of a fan of the anchor tags approach. I want a real Perma link per item.

**Comment by christophberger** [comment]
*(written yesterday)*

@robertDouglass Agreed. Furthermore, separate files are easier to model with standard Hugo concepts and techniques AFAICT. 

I reviewed the Kubernetes approach and decided to not use it as it includes some super heavy customizations, including an extra glossary script. I reckon we can do without that stuff. Hugo should be sophisticated enough for that kind of content type.

**Comment by christophberger** [comment]
Pushed a first draft of a glossary to branch `feature-faq-glossary` (d0521db).

Features:
- One file per entry
- All entries listed on the list page, with reveal/hide button
- New glossary items can be added via `hugo new content/glossary/<newentry>.md`
- Title and short description are entries in the front matter
- Detailed explanation goes into the page body

![Screen Shot 2022-02-22 at 12 57 01](https://user-images.githubusercontent.com/3835890/155146009-39754c60-e21d-43c1-9e43-8b9d4f0fbe66.png)

Todos:
- Add filter by alphabet (All - A - B - C - ... - Z - # ) or by category (like the k8s glossary does)
- Change the FAQ setup to individual files

Issues:
- Cross-links open the target entry in its own detail page. It might be preferable to unhide the entry in the glossary list instead, to maintain consistent navigation & reading experience. Not sure if this is possible without JS though.

Questions:
- Shall the FAQ be displayed in the same way as the glossary, or rather as it is currently being displayed (that is, inside text boxes)? 
- Would the FAQ need some sort of pagination and/or filtering? (In other words, how many FAQ entries are planned?)

**Comment by robertDouglass** [comment]
Nice! You can see that on the Fleek build
here ipfs://bafybeiegwe3kml7u2cg5b34aq4dlogaqafrggbchzbbtpizith35gvaxk4/glossary/
(Use Brave browser to see IPFS links natively, or use a gateway like
https://www.ipfsgate.com/)

Those preview build links are to be found behind the green checkmarks here
https://github.com/LaconicNetwork/Laconic-Documentation/branches

**Comment by robertDouglass** [comment]
For simplicity you can put all FAQs on 1 page now and we'll deal with
pagination if needed at a later stage.

**Comment by robertDouglass** [comment]
@olive-kimoto can advise on the FAQ question.

**Comment by christophberger** [comment]
Now the FAQ is also based on individual files. 93e02b8f9

- `hugo new content/faq/newentry.md`
- Question is in front matter (`question: ...`)
- Answer is in body
- Set weight in the frontmatter to impose a sort order
- Set `draft` to `false` to publish
