### ISSUE TITLE
Article: BLOG: How LN uses IPLD to preserve Merkleization of BC data

### ISSUE THREAD

**Issue by christophberger** [LaconicNetwork/Laconic-Documentation#35]
[Story Pitch](https://airtable.com/appZbLGzCXfRhSu42/tblfygfVjbHkgXgyc/viwOrzrUKGswLUPFt/recevuXyyhVsTh1fK?blocks=hide)

[Asana Task](https://app.asana.com/0/1201600522144859/1201900036947165/f)

### Target audience

- DApp developers

### Thesis

- Merkleized data is at the core of blockchain's value proposition: it allows data to be decentralized to eliminate trust. Various approaches to gaining convenient, fast access to Ethereum data exist, but these leave you with unverified, centralized data. Merkleized, off-chain data allows you to get the best of both worlds, e.g. [add use cases]. 

### Audience pain points

- Have entered into the Faustian bargain with Infura/Alchemy/The Graph and thus relinquished decentralization, but want a better solution
- Interested in Laconic, but need convincing not on an idealistic level but real use cases.

### Other context/notes/spin
- 

Everyone knows BC data is chained block-by block, but what is that like when you’re off the BC? Can it still have Merkleization?

**Comment by robertDouglass** [comment]
https://docs.google.com/document/d/1bb11vDp7BUvcn7-POu66gL5VEV_GWZ9f3M7yMkIKRM0/edit
