### ISSUE TITLE
Need categorization for FAQ

### ISSUE THREAD

**Issue by andrewjtech123** [LaconicNetwork/Laconic-Documentation#43]
We need to be able to categorize the FAQ into some subcategories. The category system should be implemented on the page as a series of headings with each FAQ appearing full width beneath. There can be a filtering or "jump to" feature at the top of the page that enables filtering the page for a specific category, or at least the ability to jump to the category heading on the page.

Some approaches we discussed to make this work:

- use metadata in Hugo
- use a folder system in Hugo 
- Hugo partials, short code 

TODO:

- [ ] @andrewjtech123 to provide a list of FAQ categories for @olive-kimoto 
- [ ] @christophberger look into implementing the categorization system in Hugo
- [ ] @olive-kimoto based on the markup we implement, style the page to display the FAQs grouped under categories with full-width display.

**Comment by andrewjtech123** [comment]
Kubernetes Hugo site for inspiration

![image](https://user-images.githubusercontent.com/6719991/161300323-9da3fe7c-ca8b-400d-bb23-2e0bee36fadc.png)

https://kubernetes.io/docs/reference/glossary

https://github.com/kubernetes/website/

**Comment by andrewjtech123** [comment]
jamboard from meeting:

![image](https://user-images.githubusercontent.com/6719991/161300762-6ac75a65-0e5d-462b-afbd-5ebdf0a7a0e2.png)

**Comment by christophberger** [comment]
To elaborate on the categories part: In today's meeting, Olive, Andrew, and I discussed the different options. Maly wants to keep it simple, so we might take only the categories row from the Kubernetes example but not take over their dynamic filtering. 

Instead, the FAQ shall render as a single page, and a click on a category would simply jump to the respective category heading on that page, as indicated in the Jamboard screenshot above.

**Comment by robertDouglass** [comment]
Let's keep it simple. We want the FAQ to be grouped into around 4 "categories" on the page. I imagine "Watchers", "Validators", "Laconic Token", and maybe one more. 

From the HTML point of view, this means adding four or so new <h1> tags to the page, and ordering the FAQ entries such that the similar topics are together.

Anything beyond that requirement is overkill and a distraction.

I would suggest *not* using the existing categories system for this, but rather either adding a new metadata field. or grouping them by subfolder.

**Comment by christophberger** [comment]
Right now I have a rudimentary solution working in branch `43-need-categorization-for-faq`. I created a new taxonomy called category and added meta fields to each FAQ article. The FAQ layout iterates over the categories, and within each category, iterates over all pages of that category and displays links to the entries. 

TODO:
- The left side bar is still not visible. The godocs theme seems to have put all the layout into a partial template named `default.html` that is used by both `list.html` and `single.html` layouts. I am looking into extracting the part that renderes the side bar to include it in `faq.html`
- Drilling down on an FAQ link from the list renders an incomplete page. Need to fix that.

**Comment by christophberger** [comment]
Created **draft** PR #50 for review. 
- Both FAQ and glossary now render fine inside the page layout (including side nav)
- Important: FAQ frontmatter must now use "title" instead of "question" 
- TODO: Cross-reference links in the glossary do not render anymore

**Comment by christophberger** [comment]
FAQ list is fully expanded now.

**Comment by christophberger** [comment]
Categories upated to: Laconic Network, Laconic Token, Validators & Member, DApps & Watchers
Occurrances of "member" changed to "partner"
