### ISSUE TITLE
Glossary layout issue 

### ISSUE THREAD

**Issue by andrewjtech123** [LaconicNetwork/Laconic-Documentation#45]
The Glossary layout currently does not have a left navigation. However, following any of the links within the glossary sends you to a different layout that has a side nav with all of the glossary items in a cluttered list. This won't scale well. 

![image](https://user-images.githubusercontent.com/6719991/161302296-f767328e-50d9-40af-88e8-b6a87f5f9b0b.png)

**Comment by christophberger** [comment]
Partially fixed by PR #50. But right now the cross-reference links do not render anymore at all. I'll have to see how to fix that.
