### ISSUE TITLE
Edits / questions to existing terms

### ISSUE THREAD

**Issue by bmann** [LaconicNetwork/Laconic-Documentation#49]
I want to paste this in here just to share it ahead of making a PR with some proper edits:

- DApp - do we need to defining dapp categories?
- devp2p - light client research
- EVM - Laconic runs the EVM as well
- Geth – review wording here
- Go-Ethereum – links to wrong thing
- Laconic Core – same as Stack?
- Laconic Network Partner – Laconic Network Participant? rather than partner?
  - Should we list Members somewhere and/or explain the LLC members?
- LNT – erc20 vs cosmos-LNT, this needs to get explained
- Laconic Stack – “plus other services” – Stack or Core? We need to explain the difference or just pick one or the other
- Optimistic Rollup – Same as Optimos bridge that we've been referencing? Or just explaining that we will use ORUs?
- Service Provider – needs expansion of what this is
- Validator – also link to SP
  - Every member (validator) HAS to be an SP? If so, probably useful to state
- Watcher – can’t be a cache AND a program. Should this be explained as a TypeScript definition and a cache, or explain that the code creates a cache -- a Watcher Cache?

**Comment by andrewjtech123** [comment]
Closing this for now since I think everything has been addressed in a couple of PRs. @bmann let me know if anything is outstanding.
