### ISSUE TITLE
Add single-topic permalink pages to FAQ & Glossary into sitemap.xml

### ISSUE THREAD

**Issue by robertDouglass** [LaconicNetwork/Laconic-Documentation#58]

**Comment by robertDouglass** [comment]
@christophberger I think this has been completed, correct?

**Comment by christophberger** [comment]
@robertDouglass – correct, I checked this in the [current build](https://bafybeic5gujuqpwmtpnxmfagss33wqi4gqwdv7ktwpi2jhehbp6gtfrmyu.on.fleek.co/sitemap.xml). 

FAQ and glossary entries are technically single pages although they are rendered as a list. Hence they go into the site map hugomatically.
