### ISSUE TITLE
Update Laconic Logo

### ISSUE THREAD

**Issue by olive-kimoto** [LaconicNetwork/Laconic-Documentation#59]
- Change to black logomark
- Make smaller, dimensions: 60x60px 

File attached
![Laconic-SVG-Black](https://user-images.githubusercontent.com/98114904/167017256-8ca9deb5-e82a-4849-b49d-6e133aca0668.svg)

**Comment by kreldjarn** [comment]
Fixed antialiasing. Do you want the logo in the footer to be 30x30px as well?

**Comment by olive-kimoto** [comment]
Yes! Thank you
