### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by olive-kimoto** [LaconicNetwork/Laconic-Documentation#60]
![laconic-favicon](https://user-images.githubusercontent.com/98114904/167017504-dcb21a32-aba7-4712-b58e-e0beb606b11c.png)

**Comment by kreldjarn** [comment]
Can you get me this logo in a 180x180px png?

**Comment by olive-kimoto** [comment]
@kreldjarn Totally! Here:
![laconic-favicon](https://user-images.githubusercontent.com/98114904/167529088-bbb15128-15e6-44fe-a87f-53ab45f71cbd.png)
