### ISSUE TITLE
Add card components to community

### ISSUE THREAD

**Issue by olive-kimoto** [LaconicNetwork/Laconic-Documentation#67]
Reference Vercel:
https://vercel.com/docs/integrations
 
<img width="802" alt="Screen Shot 2022-05-05 at 2 57 17 PM" src="https://user-images.githubusercontent.com/98114904/167032224-cf8f2751-9e1d-45b3-954c-9842fdc28200.png">

- Use icons from footer
- Make button in color: #0000f4

**Comment by kreldjarn** [comment]
I've implemented the cards, but I feel like the buttons don't really make sense with the text in the links that are currently on the Community page.

The links are part of the sentence (i.e. "Sign up for our _mailing list_", "Connect with us _on LinkedIn_"). When that text becomes part of a button, it leaves an incomplete sentence.

How do you want to resolve this?

**Comment by olive-kimoto** [comment]
@kreldjarn I think we'll axe all that copy, as they were mostly there to help hide the fact that it was text-based! Let's just do the logo icons and the name of the platform as the title, and I'll circle back with what each button will say. I don't think we'll need descriptions.
