### ISSUE TITLE
BLOG: Rick Dudley discusses Laconic Network on Interchain.fm

### ISSUE THREAD

**Issue by christophberger** [LaconicNetwork/Laconic-Documentation#68]
[Asana task](https://app.asana.com/0/0/1202237403745864/f)
Story pitches (this article combines two):
[Laconic fosters network traffic decentralization](https://airtable.com/appZbLGzCXfRhSu42/tblfygfVjbHkgXgyc/viwPmS6W0sIRTvwqq/recsahCAvkaNPGR1A?blocks=hide)
[Laconic mitigates the problem of monopolization](https://airtable.com/appZbLGzCXfRhSu42/tblfygfVjbHkgXgyc/viwPmS6W0sIRTvwqq/reclQRt0UFgHIM3dv?blocks=hide)

**Comment by zramsay** [comment]
https://www.laconic.com/blog/rick-dudley-on-interchain-fm
