### ISSUE TITLE
Adjust Headers & Spacing

### ISSUE THREAD

**Issue by olive-kimoto** [LaconicNetwork/Laconic-Documentation#71]
This is how it looks currently:
<img width="846" alt="Screen Shot 2022-05-10 at 5 52 55 PM" src="https://user-images.githubusercontent.com/98114904/167747598-4c98fe3e-1757-49aa-af27-30ad62978f31.png">

Versus this is how I envision how this can look:
<img width="848" alt="Screen Shot 2022-05-10 at 5 51 09 PM" src="https://user-images.githubusercontent.com/98114904/167747533-051ef808-accc-49b9-a22e-95958a4aae7e.png">

**Please reference examples above! Here are the itemized adjustments:**

H2 adjustments:
- [x] Increase size 
- [x] Increase font weight, I'm using "Bold" here

H3 adjustments:
- [x] Make the line beneath 3px instead of 1px
- [x] I think the spacing from the text and the line beneath needs to be larger to feel balanced 
- [x] Decrease size
- [x] Decrease font weight, I'm using "Medium" here

Spacing:
- [x] In FAQ, and anywhere else this applies: Reduce spacing between question and answer 
- [x] In FAQ, and anywhere else this applies: Increase spacing between each item

Let me know if this makes sense to you!

**Comment by kreldjarn** [comment]
It seems that the version of the font you have on the website has only three distinct weights: light, medium, and bold. I've replicated these designs as closely as I can with only three weights, but if you want it to look exactly the same you need to supply me with a version of the font that has more weight steps.

**Comment by olive-kimoto** [comment]
Ah, I'd assumed they'd uploaded the full font pack. 

You can download TT Hoves here: 
https://laconic.notion.site/Brand-Style-Guide-df34321b49014669bcd6f1e094d37a4e

**Comment by kreldjarn** [comment]
Brilliant, thank you!

**Comment by olive-kimoto** [comment]
- [ ] The H3 font weight is too heavy IMO, can we lighten it to match the example in OP?
- [ ] Can we change the grey line below H3 to match the weight of the lines of the rest on the page actually? My apologies if it's 1px!
<img width="299" alt="Screen Shot 2022-05-11 at 3 40 46 PM" src="https://user-images.githubusercontent.com/98114904/167959110-ff2b0e7f-2ee9-45bf-9174-f9fc5de80fb5.png">
