### ISSUE TITLE
Remove grey bar at bottom of page

### ISSUE THREAD

**Issue by olive-kimoto** [LaconicNetwork/Laconic-Documentation#74]
Remove this grey bar, shift content down:
<img width="1249" alt="Screen Shot 2022-05-11 at 3 33 28 PM" src="https://user-images.githubusercontent.com/98114904/167958394-3e9a75d2-3a16-46f3-9a1b-5a5f6656ac4a.png">

**Comment by kreldjarn** [comment]
I have removed the grey border. Re: shifting content down. The template assumes that there will be a copyright clause there. Is this something you plan on adding? If this is the case I do not believe we should shift it down.
