### ISSUE TITLE
Fonts on Docs site

### ISSUE THREAD

**Issue by robertDouglass** [LaconicNetwork/Laconic-Documentation#76]

**Comment by robertDouglass** [comment]
Font is not loading.

**Comment by christophberger** [comment]
Found two typos and fixed them, but the font still doesn't load.

config.toml: `primary_font_path`: `static/fonts/tthovesvariable.ttf` -> `/fonts/tthovesvariable.ttf`

assets/scss/_typography.scss: `$font_primary_path` -> `$font-primary-path`

**Comment by christophberger** [comment]
Found this in the debug output for CSS:
```
Unknown descriptor ‘,’ in @font-face rule.  Skipped to next declaration.
```
Reason: this template-driven variable assignment in `themes/godocs-3/assets/scss/style.scss`:
```scss
$font-primary: '{{ replaceRE ":wght@[0-9;]+" "" .primary_font }}', {{.primary_font_type}};
```
Removed the part starting at the comma.
