### ISSUE TITLE
Update headers and spacing

### ISSUE THREAD

**Issue by olive-kimoto** [LaconicNetwork/Laconic-Documentation#81]
- [ ] Update all grey lines across headers to match the weight of the lines in the sidebar"

Noticing this globally:
To be updated on the FAQ:
<img width="756" alt="Screen Shot 2022-07-07 at 10 15 44 AM" src="https://user-images.githubusercontent.com/98114904/177832053-4d3c9d4d-3a1c-4375-acd6-74bd523bc589.png">

To be updated on Docs:
<img width="422" alt="Screen Shot 2022-07-07 at 10 16 34 AM" src="https://user-images.githubusercontent.com/98114904/177832184-b40abe91-8637-40bd-b5ba-90788e7fcf0c.png">

- [x] Font weight on H3 should match this reference:
![image](https://user-images.githubusercontent.com/98114904/177832300-29960386-0fa2-4ea6-8ae5-ea157a4bc1bf.png)

**Comment by kreldjarn** [comment]
@olive-kimoto Re: the grey lines in the header and the sidebar: They are actually both just 1px lines, although I see what you mean, the vertical one feels aa bit thicker. Do you want me to do anything about this or should I keep them both at 1px?

**Comment by kreldjarn** [comment]
@olive-kimoto Update: I consolidated the colors of the borders — some of them were a _very slightly_ different color and maybe that's why they appeared to be different thicknesses?
